-- 코드를 작성해주세요 
-- 분기가 설마 3 6 9 12인가 이러면 쉬워지는데
SELECT 
    CASE WHEN MONTH( DIFFERENTIATION_DATE ) <= 3 THEN '1Q'
         WHEN MONTH( DIFFERENTIATION_DATE ) <= 6 THEN '2Q'
         WHEN MONTH( DIFFERENTIATION_DATE ) <= 9 THEN '3Q'
         ELSE '4Q'
    END
    AS QUARTER,
    COUNT( * )
    AS ECOLI_COUNT
    
    FROM ECOLI_DATA
    GROUP BY QUARTER
    ORDER BY QUARTER
